---
- hosts: localhost
  connection: local
  vars:
    resource_group: k8squick
    name: "{{ resource_group }}"
    location: eastus
    username: azureuser
    key_path_public: '~/.ssh/id_rsa.pub'
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
        state: present
# #az aks create --resource-group myResourceGroup --name myAKSCluster --node-count 1 --enable-addons monitoring --generate-ssh-keys
    - name: Create kluster
      azure_rm_aks: 
        name: "{{ name }}"
        resource_group: "{{ resource_group }}"
        location: "{{ location }}"
        dns_prefix: "{{ name }}"
        linux_profile:
          admin_username: "{{ username }}"
          ssh_key: "{{ lookup('file', '{{ key_path_public }}') }}"
        agent_pool_profiles:
          - name: default
            count: 1
            vm_size: Standard_D2_v2
        state: present