# https://appfleet.com/blog/integrating-ansible-and-docker-in-ci-cd-process-using-jenkins-job/
# https://docs.ansible.com/ansible/latest/collections/community/general/docker_image_module.html
---
- hosts: localhost
  connection: local
  vars_files:
    - "{{ lookup('env', 'PWD') }}/vars.yaml"  
    - "{{ lookup('env', 'PWD') }}/creds.yaml"  
  tasks:
    - name: Push Docker image to Registry
      docker_image:
        name: k8s-api
        build:
          path: /opt/docker
          pull: true
        state: present
        tag: "latest"
        force_tag: yes
        repository: ericstephens/k8s-api:latest
        push: yes
        - source: build