FROM python:3.9-alpine3.12
ENV PYTHONUNBUFFERED 1
RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY ./app /app
EXPOSE 5000
CMD [ "python", "app.py" ]