apiVersion: v1
kind: Service
metadata:
  name: reversomatic-svc
  labels:
    app: reversomatic
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30001
    protocol: TCP
  selector:
    app: reversomatic